title: All About Me
theme: minima
author: Sophia Olakangil <3
email: solakangil@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This website is a profile for Sophia Olakangil and all of her amazing accomplishments

# social links

<a href="https://www.instagram.com/">Instagram</a> # DO NOT include the @ character, or else the build will fail!
<a href="https://www.snapchat.com/">Snapchat</a> # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
