title: All About Me
theme: minima
author: Sophia Olakangil
email: solakangil@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This website is a profile for Sophia Olakangil and all of her amazing accomplishments

# social links
twitter_username: sophia.ola # DO NOT include the @ character, or else the build will fail!
instagram_username:  sophie.olaa # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
